# config/tts_config.yaml
tts_settings:
    en:
        voice_id: "en-US-JennyNeural"
        rate: "+0%"
        volume: "100%"
    zh:
        voice_id: "zh-CN-XiaoxiaoNeural"
        rate: "+0%"
        volume: "100%"
    ja:
        voice_id: "ja-JP-NanamiNeural"
        rate: "+0%"
        volume: "100%"

cache_settings:
    max_age_days: 7
    cache_dir: "/tmp/tts_cache"
